class VsCurrency < ApplicationRecord
	def to_s
		case symbol
		# Crypto Currencies
		when 'btc' then 'Bitcoin (₿)'
		when 'eth' then 'Ethereum (ETH)'
		when 'ltc' then 'Litecoin (LTC)'
		when 'bnb' then 'Binance Coin (BNB)'
		when 'xrp' then 'Ripple (XRP)'
		# Fiat Currencies
		when 'usd' then 'US Dollar ($)'
		when 'eur' then 'Euro (€)'
		when 'gbp' then	'Pound Sterling (£)'
		when 'aed' then 'Emirati Dirham (د.إ)'
		when 'ars' then 'Argentine Peso ($)'
		when 'bdt' then 'Bangladeshi Taka (৳)'
		when 'bhd' then 'Bahraini Dinar (د.ب)'
		when 'bmd' then 'Bermudan Dollar ($)'
		when 'cad' then 'Canadian Dollar ($)'
		when 'aud' then 'Australian Dollar ($)'
		when 'chf' then 'Swiss franc (CHF)'
		when 'clp' then 'Chilean Peso ($)'
		when 'czk' then 'Czech Koruna (Kč)'
		when 'dkk' then 'Danish Krone (kr.)'
		when 'cny' then 'Yuan/Renminbi (元 / ¥)'
		when 'hkd' then 'Hong Kong Dollar ($)'
		when 'brl' then 'Brazilian Real (R$)'
		when 'huf' then 'Hungarian forint (Ft)'
		when 'idr' then 'Indonesian Rupiah (Rp)'
		when 'ils' then 'Israeli new shekel (₪)'
		when 'inr' then 'Indian Rupee (₹)'
		when 'jpy' then 'Japanese Yen (¥)'
		when 'krw' then 'South Korean Won (₩)'
		when 'kwd' then 'Kuwaiti Dinar (د.ك)'
		when 'lkr' then 'Sri Lankan Rupee (₨)'
		when 'mmk' then 'Myanmar Kyat (K)'
		when 'mxn' then 'Mexican Peso ($)'
		when 'myr' then 'Malaysian Ringgit (RM)'
		when 'nok' then 'Norwegian krone (kr)'
		when 'nzd' then 'New Zealand dollar ($)'
		when 'php' then 'Philippine peso ($)'
		when 'pkr' then 'Pakistani rupee (₨)'
		when 'pln' then 'Polish złoty (zł)'
		when 'rub' then 'Russian ruble (₽)'
		when 'sar' then 'Saudi riyal (ر.س)'
		when 'sek' then 'Swedish krona (kr)'
		when 'sgd' then 'Singapore dollar ($)'
		when 'thb' then 'Thai baht (฿)'
		when 'try' then 'Turkish lira (₺)'
		when 'twd' then 'New Taiwan dollar ($)'
		when 'uah' then 'Ukrainian hryvnia (₴)'
		when 'vef' then 'Venezuelan bolívar (Bs.)'
		when 'vnd' then 'Vietnamese dong (₫)'
		when 'zar' then 'South African rand (R)'
		when 'xdr' then 'IMF Special Drawing Rights'
		when 'xag' then 'Silver Exchange Rate'
		when 'xau' then 'Gold Exchange Rate'
		else
			symbol.upcase
		end
	end
end
